spring:
  application:
    name: jwt_cookie_study

  datasource:
    url: jdbc:postgresql://localhost:5432/springstudy
    username: jomingu
    password: 43054305
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: codingapple

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 30m

jwt:
  secret: "ZW5eXQip7qKpihN8712tAUMNu3tMOevdBgSgpCySTmxMuRSxaVhCLIAPr5aMw7vk"